### ISSUE TITLE
Can't run app on M1 Mac with Monterey

### ISSUE THREAD

**Issue by daniel-toman** [tedsmith/quickhash#103]
Hello, I just discovered your app and would love to use it for creating checksum verification reports of file copies on Mac. However when I tried to run the downloaded app on my M1 Mac Studio, it just fails with the error: **The application “Quickhash-GUI” can’t be opened.** I have MacOS Monterey 12.3.1 installed which is basically the version it shipped with, I think.

I have tried right-clicking the app and choosing Open, multiple times, but the same error message pops up. Usually that will do the trick for apps from Unverified Developers or whatever Apple calls it. 

I also notice that it seems like the application icon is missing? Is there a way to get this working on my M1 Monterey Mac, or perhaps it could work in a future version? Thank you! Screenshots attached.

![Screen Shot 2022-09-01 at 3 34 48 PM](https://user-images.githubusercontent.com/1903582/188024771-7c9494f0-81f3-4cf9-81bc-2fec2d351a55.png)
![Screen Shot 2022-09-01 at 3 39 10 PM](https://user-images.githubusercontent.com/1903582/188024772-638d9352-6630-413c-a699-c7e309ea7aad.png)

**Comment by daniel-toman** [comment]
I found the answer on your website, I needed to run the command:
`chmod +x Quickhash-GUI.app/Contents/MacOS/Quickhash-GUI`

And then I needed to right-click the app, and choose **Open**, and then accept the warning. 

Suggestion: [the FAQ page](https://www.quickhash-gui.org/about-quickhash-gui/faqs/) on your website that recommends this command, actually has some typos in it: `chmod +x QuickHash.app/Content/MacOS/Quickhash-GUI`
(should be "Quickhash-GUI.app" and "Contents")

**Comment by tedsmith** [comment]
Apologies for the time taken in getting back. 

Yes - you are right that the app needs to be given executable permission. One of the many things on the To Do list it work out how to package it better for OSX. But frankly, OSX is a nightmare to develop for and I have thought several times of just dropping it entirely. Only due to the fact that a fiar few folks find it useful to use it on there do I persist. 

Thanks for typo observation - I'll work to correct that.
