### ISSUE TITLE
dpkg-deb: error: archive 'quickhash_3.3.3-1_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up

### ISSUE THREAD

**Issue by dotbanana** [tedsmith/quickhash#115]
Cannot install under debian 12. 
dpkg doesn't support this obscure compression format you chose. 
There are workarounds but this is tedious really. 
When offering a .deb it should be compatible with debian.  
Thanks anyways

Best Regards

**Comment by darealshinji** [comment]
I wouldn't call [zstd](https://en.wikipedia.org/wiki/Zstd) obscure but it's good to know it doesn't work on Debian. It was automatically chosen by the build tools.

**Comment by darealshinji** [comment]
Doing a quick check on https://packages.debian.org shows that even on older Debian versions the compression is xz (I've check the binutils package for amd4). I know that xz has also been working for a long time on Ubuntu.

**Comment by tedsmith** [comment]
That's good to know and thank you for taking the time and effort to check this out. I'm sure .Banana will be pleased to read this. I'm going to try and get v3.3.4 released tonight if I can get some time amidst family carnage. So I'll pull packaging and re package it so that .banana can enjoy the benefits of Quickhash. It will also include 14 translations of the user manual that I've created with AWS Translate....at a good price given what it's done but a price higher than I was expecting! 😖

**Comment by darealshinji** [comment]
The last release is now using xz compression.
