### ISSUE TITLE
UserManual.pdf source?

### ISSUE THREAD

**Issue by darealshinji** [tedsmith/quickhash#19]
Since your project is GPL licensed, shouldn't the original office document that UserManual.pdf was exported from be uploaded too?

**Comment by tedsmith** [comment]
I did wonder that, initially, but then, what for? The PDF is a direct export of the ODT file, and all that providing the ODT file enable is for people to create and distribute alternative versions of the PDF, potentially. I found, the other day, a copy of the PDF for sale!!! I contacted the website to ask why they are listing part of an open-source user manual that anybody can download from my website, and I got a load of garbage about American copyright law etc. 

So, unless I can be persuaded otherwise, and as the ODT file is not needed to compile the source code, I was not planning on adding it. The only reason I might (aside from your point) is that of version control of course. I do keep having to be careful not to overwrite my ODT file with the wrong version using a changed version. Submitting to GitHub would help with that.

**Comment by darealshinji** [comment]
The main reason I'm asking is that the ODT file could be considered the "source" format of the exported PDF document. And GPL after all requires the source to be made available. On the other side it's mainly intended to be used on software, where it's pretty clear what counts as "source", which is not always the case for other materials, such as images or sound files. It's also quite easy to import the PDF in LibreOffice, edit stuff and export it as a new document.

As for the sale stuff, well, free software and documentation can always be sold. You must move to a more restrictive custom license or a non-free Creative Commons license (i.e. cc-by-nc-sa) if you don't want that. If you publish the ODT document under GPL that website _may_ be forced to publish the sources too (even for free, I think). But I'm not a lawyer. Maybe you can contact someone from FSF.org and ask for help.

**Comment by tedsmith** [comment]
Mmm, rightly or wrongly, I think I'll keep the master version offline and local to my machine for now. If you want a copy of it, I will happily e-mail it to you, but I think for now I'd rather keep off GitHub.
