### ISSUE TITLE
unused source files

### ISSUE THREAD

**Issue by darealshinji** [tedsmith/quickhash#20]
I just wanted to inform you that the following source files are not used (at least not on Linux):
```
GPTMBR.pas
md5customised.pas
MD5TransformEnhancedAssemblyCodei386.inc
MD5TransformEnhanced.pas
uGPT.pas
unit2 - Copy.lfm
unit2_old.lrs
```

**Comment by tedsmith** [comment]
GPTMBR.pas and uGPT.pas are used to show technical disk data in the disk hashing module on Windows. 

The MD5 files are the remains of pre-v2.8.0 before I puilled in HashLib4Pascal unit. I had kept them more because they are just a useful reference of assembly. I guess we could take them out now. 

The two old unit files can definitely go.

**Comment by tedsmith** [comment]
There's also : 
 	SHA1TransformEnhanced.pas
	SHA1TransformEnhancedAssemblyCodei386.inc
same theory as for MD5. Fairly sure they are not used now either.

**Comment by darealshinji** [comment]
Indeed, SHA1TransformEnhanced seems not to be used. But to be able to build without it its reference in `project1.lpr` needs to be removed too.

**Comment by tedsmith** [comment]
Removed in latest commit afb41ec which relates to v2.8.2. Well spotted.
