### ISSUE TITLE
Disk hashing module on CDs

### ISSUE THREAD

**Issue by marcelofernandez** [tedsmith/quickhash#22]
Hi, I was trying this functionality in Windows 10 with a DVD drive and a DVD disk, but can't make it work. I'm getting "Could not get exclusive disk access OS error and code: The system cannot find the file especified."

BTW, the DVD Drive does not appear in the "Physical Disk" list, I've just changed the Selected Item to "PHYSICALDRIVE1". I've disabled antivirus, and I can't just easily umount the disk like in Linux :-(

![virtualbox_windows 10_29_05_2017_12_49_13](https://cloud.githubusercontent.com/assets/1588034/26555891/b4301912-446d-11e7-9c8c-5c8c03342cc8.png)

Regards

**Comment by tedsmith** [comment]
I can't say I ever tested it with DVD or CD. It's designed for physical disks more so that have traditional sectors reported by disk hardware. DVD, for example, typically has 1024 byte sectors. 

Secondly, DVD and so on are more typically represented as logical volumes because, unlike normal disk, if a DVD is not formatted it cannot be addressed anyway. And by formatting it, it becomes logical. 

Anyway, try running as administrator if you haven't already. The error you state is usually given when the user doesn't have sufficient privilege or when something else with higher privilege has locked access. By the looks of it, eve accessing your host drive is refusing access, suggesting insufficient privilege. especially likely on Windows 10. 

Ted.

**Comment by tedsmith** [comment]
Not heard back. Closed.

**Comment by marcelofernandez** [comment]
Hi Ted,

Sorry I didn't reply before. Yes, I've tried running as administrator, and/or a Logical Volume.

Look:
https://www.youtube.com/watch?v=EQ8fpOaXdnM

Regards

**Comment by tedsmith** [comment]
You're right...I tried it last night with a valid DVD disk in a valid DVD drive and it did not detect it. I'll look into it...thanks

**Comment by binarylandscapes** [comment]
Any update on providing ability to check sha of discs? Would love to have this

**Comment by tedsmith** [comment]
Better late than never @binarylandscapes and @marcelofernandez but according to tests conducted by a couple of my friends, v3.3.0 which will be released on Saturday 29th May over at www.quickhash-gui.org does now appear to work for CD\DVD. Obviously, only as a logical volume (as you cant address a DVD as a physical disk). But they found that the disk module loaded OK, could be read, and hashed, and the computed hash was correct. So I'll mark this as closed, now, 4 years after it was raised, and I'm sorry it took me so long.
