### ISSUE TITLE
Issues with disk hashing on Linux

### ISSUE THREAD

**Issue by darealshinji** [tedsmith/quickhash#25]
I seem to have some issues with disk hashing on Linux because `udisks` is not an available command. `udisksctl` however is a command available with the Ubuntu package `udisks2`.

**Comment by tedsmith** [comment]
That could cause us some issues because I thought udisks was fairly mainstream within the desktop Linux systems. I use Linux Mint and QH v2.8.2 for Linux works fine on that. I assume you're using Ubuntu then, and udisks is not on it? 

![screenshot-4](https://user-images.githubusercontent.com/1560598/27203925-0a747272-5220-11e7-9bff-b54e716ae1de.png)
![screenshot-5](https://user-images.githubusercontent.com/1560598/27203926-0a77dafc-5220-11e7-805f-d653f46a8d6a.png)

**Comment by tedsmith** [comment]
Fixed in commit ff67c5e9161a6aa8c37f6b17eeb7214e2dd56641 - udisksctl now used instead. I noticed that Zorin OS also could not utilise this, as udisks is quite old now and has long been superseeded by udisks2, as you stated back in early 2017. Some additional improvements also added (like disk size shown in friendly format as well as pure byte value)
