### ISSUE TITLE
error message on the File tab (v3.0.0)

### ISSUE THREAD

**Issue by darealshinji** [tedsmith/quickhash#40]
When I click "Select File" on the File tab and then just close the window, I get the following error message: "An error occured opening the file. Error code: Bad address"

This doesn't happen with the file selection on other tabs.

By the way, now I see that "occurred" should be written with two Rs.

**Comment by tedsmith** [comment]
I think I added an explicit handle error message for that button, but didn't for the others. So its not a bug especially. Its telling the user that QuickHash failed to initiate a handle as no file was given. But I'll address it for the next release to make it more consistent with the other buttons as you say.

**Comment by darealshinji** [comment]
Is canceling the file selection window really worth throwing a message?
Most programs just don't do anything in that case.

**Comment by tedsmith** [comment]
Not at all. I meant to say I added that a long time ago back when quickhash just a text and s ingle file program. It’s just been such a long time since I actually pressed cancel in that tab I’d forgot about it. We can take it out. My point was that it doesn’t do any harm. It’s not doing anything wrong strictly speaking but I agree...largely pointless.

**Comment by tedsmith** [comment]
Corrected in commit 90ca2437cc9079abcd94356cfedf08c47640156f and no error is now shown for that button if the user clicks cancel.
