### ISSUE TITLE
make sqlite database name more unique

### ISSUE THREAD

**Issue by darealshinji** [tedsmith/quickhash#45]
Starting two instances at the same time with `./QuickHash-Linux-x64 & ./QuickHash-Linux-x64` makes one of them report an error that no database can be created (because the filename is already in use).

Not an issue for most people but it should still be easy to fix.

You could use the process ID (`GetProcessID()`) or a GUID (`CreateGUID()`, `GUIDToString()`) or create a temporary filename with `GetTempFileName()`.

**Comment by tedsmith** [comment]
That’s weird! That has come up already and I thought I’d fixed it to create a dB with date and time so that unless you launched two instances in the same second it would work by creating two databases with different names. I will have to look again 


Sent from Yahoo Mail for iPhone


On Tuesday, July 24, 2018, 2:15 pm, darealshinji <notifications@github.com> wrote:


Starting two instances at the same time with ./QuickHash-Linux-x64 & ./QuickHash-Linux-x64 makes one of them report an error that no database can be created (because the filename is already in use).

Not an issue for most people but it should still be easy to fix.

You could use the process ID (GetProcessID()) or a GUID (CreateGUID(), GUIDToString()) or create a temporary filename with GetTempFileName().

**Comment by darealshinji** [comment]
> [..] so that unless you launched two instances in the same second it would work [..]

That's the issue, if you launch two instances at the same time (accidentally or maybe even on purpose) the two databases will have the same name so one of them instances can't access the database. The functions mentioned in the first post should help to create more unique filenames so even in strange cases each instance will have its unique database file.

**Comment by tedsmith** [comment]
But how are you launching two instances in the exact same second? Just moving the mouse and double clicking a second time must surely take more than a second? 


Sent from Yahoo Mail for iPhone


On Tuesday, July 24, 2018, 4:17 pm, darealshinji <notifications@github.com> wrote:



[..] so that unless you launched two instances in the same second it would work [..]


That's the issue, if you launch two instances at the same time (accidentally or maybe even on purpose) the two databases will have the same name so one of them instances can't access the database. The functions mentioned in the first post should help to create more unique filenames so even in strange cases each instance will have its unique database file.

**Comment by darealshinji** [comment]
> But how are you launching two instances in the exact same second?

Open a termnial and enter this: `./QuickHash-Linux-x64 & ./QuickHash-Linux-x64`

_One_ `&` symbol in a shell means the second command will be launched immediately after the first, even if the process was not finished yet (so even if a launched program is still running).

**Comment by tedsmith** [comment]
Ah, OK. I see. Well I can't say I anticipated that kind of use, but you are quite correct. 

And your fix looks good. I see no reason how that couldn't work on OSX either so I will merge it all to master. I didn't actually realise you could use CreateGUID to essentially use as a randomiser. Thanks as always.
