### ISSUE TITLE
compiler warnings and other small things

### ISSUE THREAD

**Issue by darealshinji** [tedsmith/quickhash#58]
I've created a new branch with an attempt to fix some compiler warnings and other small things:
https://github.com/tedsmith/quickhash/tree/3.0.4-small-fixes

Please have a look at it. If there's stuff you don't like I can rebase the branch.

**Comment by tedsmith** [comment]
Thanks. I will take a look when I can. 
In the meantime can you change the branch name to 3.0.5 because 3.0.4 is out and current stable. So any new fixes will be for v3.0.5 


Sent from Yahoo Mail for iPhone


On Tuesday, January 22, 2019, 6:10 pm, darealshinji <notifications@github.com> wrote:


I've created a new branch with an attempt to fix some compiler warnings and other small things:
https://github.com/tedsmith/quickhash/tree/3.0.4-small-fixes

Please have a look at it. If there's stuff you don't like I can rebase the branch.

**Comment by darealshinji** [comment]
Closing this because of commit https://github.com/tedsmith/quickhash/commit/aaeb6ebca9e9d70a80927411fdbed08a249f6349
