### ISSUE TITLE
Save settings in user directory

### ISSUE THREAD

**Issue by darealshinji** [tedsmith/quickhash#6]
Currently the `QHSettings.xml` file is saved in the directory from where the binary is executed. I think it would be better to save the file in the user directory, at least on Linux. For Linux I would suggest `$HOME/.config/QuickHash/` or `$HOME/.config/`

**Comment by tedsmith** [comment]
Yes, good point. I think that will be a very good idea for Apple Mac OSX especially because I think there will be issues with it saving the file on that platform. 
 

    On Wednesday, 21 December 2016, 7:35, darealshinji <notifications@github.com> wrote:
 

 Currently the QHSettings.xml file is saved in the directory from where the binary is executed. I think it would be better to save the file in the user directory, at least on Linux. For Linux I would suggest $HOME/.config/QuickHash/ or $HOME/.config/—

**Comment by darealshinji** [comment]
You can try to use [GetEnvironmentVariable()](http://lazarus-ccr.sourceforge.net/docs/rtl/sysutils/getenvironmentvariable.html) to get the value of `$HOME` on OSX and Linux.

**Comment by darealshinji** [comment]
I did some research and most simple approach seems to be to set an empty filename. On Linux the settings will be saved in the home directory as .PROGRAMNAME and according to the Lazarus wiki on Windows and OSX it will be saved in the application directory as PROGRAMNAME.xml.

**Comment by tedsmith** [comment]
That looks fine to me...well researched. It's an important thing to get incorporated and it was something I partly overlooked when compiling the versions for Linux and Max OSX

Have you got a commit of this that you could push up, or would you rather I do it at some stage?
