### ISSUE TITLE
Precompiled binaries as GitHub assets

### ISSUE THREAD

**Issue by c0bw3b** [tedsmith/quickhash#94]
Hello,

Thanks for making Quickhash. It's a nifty tool, the right balance between feature-complete and easy-to-use. :)

Would you be willing to add the precompiled binaries archives as assets on each releases (tags) here on Github?
It would provide an additional download source and maybe reduce the network load on your own infrastructure hosting the website.

**Comment by tedsmith** [comment]
Hi

Thanks for your thoughts. You're perhaps right. It has crossed my mind before to just ditch the website entirely and host everything here, seeing as the AWS fees are not inexpensive relative to a free project. But the domain name is so well established now, with thousands of blogs etc linking to it, I fear it might be unwise for me to do that. But I'm not sure I want to "cross host" because it makes it a bit confusing and is another step at release time. It's already quite a faff compiling for WIndows, Linux and then OSX, and then hashing, uploading etc. But I'll keep it in mind. Thanks.
